name: CI/CD Pipeline

#1. Trigger
on:
  push:
    branches: ["main", "develop"]
  pull_request:
    branches: ["main"]

# 2. Jobs
jobs:
  # Job A: QUality control
  test-and-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependancies
        run: |
          pip install flake8
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run Linter (Check for sloppy code)
        run: |
          # Stop the buiild if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

  # Job B: The Builder
  build-container:
    needs: test-and-lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and Export
        uses: docker/build-push-action@v4
        with: 
          context: .
          push: false
          tags: my-app:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
